import matplotlib.pyplot as plt

def plot_ts(df):
    plt.figure(figsize=(16, 8))
    plt.subplot(3, 2, 1)
    plt.plot(df.index, df['Último'], color='blue')
    plt.xlabel('Data')
    plt.ylabel('Último Fechamento')
    plt.title('Variação do Último Fechamento')
    plt.subplot(3, 2, 2)
    plt.plot(df.index, df['Abertura'], color='green')
    plt.xlabel('Data')
    plt.ylabel('Abertura')
    plt.title('Variação de Aberturas')
    plt.subplot(3, 2, 3)
    plt.plot(df.index, df['Máxima'], color='orange')
    plt.xlabel('Data')
    plt.ylabel('Máxima')
    plt.title('Valor Máximo no dia')
    plt.subplot(3, 2, 4)
    plt.plot(df.index, df['Mínima'], color='red')
    plt.xlabel('Data')
    plt.ylabel('Mínima')
    plt.title('Valor Mínimo do dia')
    plt.subplot(3, 2, 5)
    plt.plot(df.index, df['Vol.'], color='purple')
    plt.xlabel('Data')
    plt.ylabel('Volume')
    plt.title('Volume de Ações no dia')
    plt.subplot(3, 2, 6)
    plt.plot(df.index, df['Var%'], color='cyan')
    plt.xlabel('Data')
    plt.ylabel('Variação')
    plt.title('Variação das Ações no dia')
    plt.tight_layout()
    plt.show()